[package]
name = "generate"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
image-builder = "1.0.2"
quote = "1.0.38"
termcolor = "1.4.1"
syn = "2.0"
proc-macro2 = "1.0"